[package]
name = "countdown-numbers"
version = "0.1.0"
authors = ["Rodney Johnson <ask@rodneylab.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/rodneylab/countdown-numbers"
rust-version = "1.60"
description = "Trying Ratatui TUI ğŸ§‘ğŸ½â€ğŸ³ building a text-based UI number game in the Terminal ğŸ–¥ï¸ in Rust with Ratatui immediate mode rendering."

[dependencies]
crossterm = "0.27.0"
num_parser = "1.0.2"
rand = "0.8.5"
ratatui = "0.26.3"
